org.gradle.caching=true
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
fabric.loom.multiProjectOptimisation=true

project.group=com.iamkaf.endersight
project.plugins=3.0-SNAPSHOT

mod.name=Ender Sight
mod.authors=iamkaf
mod.id=endersight
mod.license=PolyForm-Shield-1.0.0
mod.credits=
mod.description=Ender items that work by sight: teleport to what you see, guide Eyes of Ender anywhere, mark targets through walls, and set redstone eyes on watch.

publish.dry-run=false
publish.curseforge.id=1203233
publish.modrinth.id=y5UyihEq
publish.release-type=release
publish.game-versions=auto
dependencies.modrinth.required=amber
dependencies.curseforge.required=amber-lib
environments.client=required
environments.server=required

mixin.compat.common=JAVA_21
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_21
mixin.compat.neoforge=JAVA_21
